# Generated by Django 4.1.3 on 2022-12-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingtoolapp', '0004_applicationsmodel_user_bookingsmodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='employee_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='employee_name',
            field=models.CharField(max_length=100),
        ),
    ]
