# Generated by Django 4.1.3 on 2022-12-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingtoolapp', '0005_alter_productsmodel_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsmodel',
            name='employee_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationsmodel',
            name='employee_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingsmodel',
            name='employee_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookingsmodel',
            name='employee_name',
            field=models.CharField(max_length=100),
        ),
    ]
