# Generated by Django 4.1.3 on 2022-12-08 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketingtoolapp', '0006_alter_applicationsmodel_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(null=True)),
                ('employee_name', models.CharField(max_length=100, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=100)),
                ('your_requirement', models.CharField(choices=[('pycharm', 'Pycharm'), ('vscode', 'VSCode'), ('python', 'Python'), ('java', 'Java'), ('mysql', 'MySql'), ('ecllipse', 'Ecllipse'), ('other', 'Other')], default='Other', max_length=100)),
                ('Reason', models.TextField()),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(null=True)),
                ('employee_name', models.CharField(max_length=100, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=100)),
                ('your_requirement', models.CharField(choices=[('cubical', 'Cubical'), ('training room', 'Training Room'), ('board room', 'Board Room'), ('interview room', 'Interview Room'), ('other', 'Other')], default='Other', max_length=100)),
                ('Reason', models.TextField()),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(null=True)),
                ('employee_name', models.CharField(max_length=100, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=100)),
                ('your_requirement', models.CharField(choices=[('laptop', 'Laptop'), ('mouse', 'Mouse'), ('headset', 'Headset'), ('keyboard', 'Keyboard'), ('other', 'Other')], default='Other', max_length=100)),
                ('Reason', models.TextField()),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StationaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(null=True)),
                ('employee_name', models.CharField(max_length=100, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=100)),
                ('your_requirement', models.CharField(choices=[('bag', 'Bag'), ('pen', 'Pen'), ('pencil', 'Pencil')], default='Other', max_length=100)),
                ('Reason', models.TextField()),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookingsmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productsmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='ApplicationsModel',
        ),
        migrations.DeleteModel(
            name='BookingsModel',
        ),
        migrations.DeleteModel(
            name='ProductsModel',
        ),
    ]
