# Generated by Django 4.1.3 on 2022-12-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingtoolapp', '0007_applicationmodel_bookingmodel_productmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationarymodel',
            name='your_requirement',
            field=models.CharField(choices=[('bag', 'Bag'), ('pen', 'Pen'), ('pencil', 'Pencil'), ('paper', 'Paper'), ('stapler', 'Stapler'), ('book', 'Book'), ('other', 'Other')], default='Other', max_length=100),
        ),
    ]
