# Generated by Django 4.1.3 on 2022-12-08 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingtoolapp', '0008_alter_stationarymodel_your_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='request_raised_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='request_raised_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='request_raised_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='stationarymodel',
            name='request_raised_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
