# Generated by Django 4.1.3 on 2022-12-08 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingtoolapp', '0010_alter_stationarymodel_request_raised_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='request_raised_at',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='request_raised_at',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='request_raised_at',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='stationarymodel',
            name='request_raised_at',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
