# Generated by Django 4.1.3 on 2022-12-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingtoolapp', '0011_alter_applicationmodel_request_raised_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='request_raised_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='request_raised_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='request_raised_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stationarymodel',
            name='request_raised_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
