# Generated by Django 4.1.3 on 2022-12-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingtoolapp', '0012_alter_applicationmodel_request_raised_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='status',
            field=models.CharField(choices=[('raised', 'raised'), ('accept', 'accept'), ('reject', 'reject'), ('complete', 'complete')], default='raised', max_length=100),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='status',
            field=models.CharField(choices=[('raised', 'raised'), ('accept', 'accept'), ('reject', 'reject'), ('complete', 'complete')], default='raised', max_length=100),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='status',
            field=models.CharField(choices=[('raised', 'raised'), ('accept', 'accept'), ('reject', 'reject'), ('complete', 'complete')], default='raised', max_length=100),
        ),
        migrations.AddField(
            model_name='stationarymodel',
            name='status',
            field=models.CharField(choices=[('raised', 'raised'), ('accept', 'accept'), ('reject', 'reject'), ('complete', 'complete')], default='raised', max_length=100),
        ),
    ]
