# Generated by Django 4.1.3 on 2022-12-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingtoolapp', '0014_alter_applicationmodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='status',
            field=models.CharField(choices=[('raised', 'raised'), ('accepted', 'accepted'), ('reject', 'reject'), ('complete', 'complete')], default='raised', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='status',
            field=models.CharField(choices=[('raised', 'raised'), ('accepted', 'accepted'), ('reject', 'reject'), ('complete', 'complete')], default='raised', max_length=100),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='status',
            field=models.CharField(choices=[('raised', 'raised'), ('accepted', 'accepted'), ('reject', 'reject'), ('complete', 'complete')], default='raised', max_length=100),
        ),
        migrations.AlterField(
            model_name='stationarymodel',
            name='status',
            field=models.CharField(choices=[('raised', 'raised'), ('accepted', 'accepted'), ('reject', 'reject'), ('complete', 'complete')], default='raised', max_length=100),
        ),
    ]
