# Generated by Django 4.1.3 on 2022-12-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingtoolapp', '0016_alter_applicationmodel_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(default='i5J3aU', max_length=10, unique=True)),
                ('Subject', models.CharField(max_length=100)),
                ('Severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=100)),
                ('Type', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('cubical', 'Cubical'), ('training room', 'Training Room'), ('board room', 'Board Room'), ('conference', 'Conference'), ('stationary', 'Stationary'), ('other', 'Other')], default='other', max_length=100)),
                ('Manager', models.CharField(max_length=100)),
                ('Remarks', models.TextField()),
            ],
        ),
    ]
