# Generated by Django 4.1.3 on 2022-12-12 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketingtoolapp', '0018_ticket_user_alter_ticket_ticket_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='Reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='status',
            field=models.CharField(choices=[('raised', 'raised'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('completed', 'completed')], default='raised', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='your_requirement',
            field=models.CharField(choices=[('cubical', 'Cubical'), ('training room', 'Training Room'), ('board room', 'Board Room'), ('interview room', 'Interview Room'), ('other', 'Other')], default='Other', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_no',
            field=models.CharField(default='OJ-POA9X7', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
