# Generated by Django 4.1.3 on 2022-12-12 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingtoolapp', '0019_alter_bookingmodel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='request_raised_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_no',
            field=models.CharField(default='OJ-E1PY8X', max_length=10, unique=True),
        ),
    ]
