# Generated by Django 4.1.3 on 2022-12-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingtoolapp', '0023_alter_ticket_ticket_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comment',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_no',
            field=models.CharField(default='OJ-673VUL', max_length=10, unique=True),
        ),
    ]
